//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Programacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_Nomina
    {
        public int Id { get; set; }
        public string Ano { get; set; }
        public string Mes { get; set; }
        public int Monto_Total { get; set; }
        public int EmpleadosId { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
