//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Programacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleados> EmpleadosSet { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Cargos> CargosSet { get; set; }
        public virtual DbSet<Cal_Nomina> Cal_NominaSet { get; set; }
        public virtual DbSet<Licencias> LicenciasSet { get; set; }
        public virtual DbSet<Permisos> PermisosSet { get; set; }
        public virtual DbSet<Vacaciones> VacacionesSet { get; set; }
        public virtual DbSet<Salida_Empleados> Salida_EmpleadosSet { get; set; }
    }
}
